//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfakimAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OfakimDBEntities : DbContext
    {
        public OfakimDBEntities()
            : base("name=OfakimDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblGender> tblGender { get; set; }
        public virtual DbSet<tblUsers> tblUsers { get; set; }
    
        public virtual ObjectResult<spAddUser_Result> spAddUser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spAddUser_Result>("spAddUser");
        }
    }
}
