//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfakimAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsers
    {
        public decimal Id { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Phone { get; set; }
        public string FullName { get; set; }
        public Nullable<decimal> Gender { get; set; }
    
        public virtual tblGender tblGender { get; set; }
    }
}
